"""Build the base-map geometry for the Resolve UI (Natural Earth 10m, public domain)."""
import json
from pathlib import Path
# Inputs: download from github.com/nvkelso/natural-earth-vector (geojson/):
#   ne_10m_admin_0_countries.geojson, ne_10m_admin_1_states_provinces.geojson
# Run from the folder holding them: python ui/tools/build_geo.py
from shapely.geometry import shape, box, mapping, MultiLineString, LineString, Polygon, MultiPolygon
from shapely.ops import unary_union, linemerge

BBOX = box(60.0, 3.0, 104.0, 40.0)
TOL_LAND = 0.012
TOL_LINE = 0.012

a0 = json.load(open('ne_10m_admin_0_countries.geojson'))
a1 = json.load(open('ne_10m_admin_1_states_provinces.geojson'))

countries = {}
for f in a0['features']:
    g = shape(f['geometry'])
    if not g.intersects(BBOX):
        continue
    countries[f['properties']['ADM0_A3']] = g.buffer(0)
print('countries in bbox:', sorted(countries))

land = unary_union(list(countries.values())).intersection(BBOX)
land = land.simplify(TOL_LAND, preserve_topology=True)

def rings_of(geom):
    polys = [geom] if isinstance(geom, Polygon) else list(getattr(geom, 'geoms', []))
    out = []
    for p in polys:
        if not isinstance(p, Polygon) or p.area < 0.0004:   # drop specks < ~5 km2
            continue
        out.append([[round(x, 3), round(y, 3)] for x, y in p.exterior.coords])
        for hole in p.interiors:
            out.append([[round(x, 3), round(y, 3)] for x, y in hole.coords])
    return out

def lines_of(geom):
    if geom.is_empty:
        return []
    if isinstance(geom, LineString):
        parts = [geom]
    else:
        parts = [g for g in getattr(geom, 'geoms', []) if isinstance(g, LineString)]
    merged = linemerge(MultiLineString(parts)) if len(parts) > 1 else (parts[0] if parts else None)
    if merged is None:
        return []
    parts = [merged] if isinstance(merged, LineString) else list(merged.geoms)
    out = []
    for p in parts:
        p = p.simplify(TOL_LINE)
        if p.length < 0.02:
            continue
        out.append([[round(x, 3), round(y, 3)] for x, y in p.coords])
    return out

def shared(a, b):
    inter = a.boundary.intersection(b.boundary.buffer(0.0005))
    # keep only linear parts
    return inter

# International borders (land boundaries between neighbours)
codes = sorted(countries)
intl = []
for i, a in enumerate(codes):
    for b in codes[i+1:]:
        if countries[a].distance(countries[b]) > 0.01:
            continue
        s = countries[a].boundary.intersection(countries[b].buffer(0.002))
        s = s.intersection(BBOX)
        intl.extend(lines_of(s))
print('intl border lines:', len(intl))

# Indian state boundaries (internal only)
states = {}
for f in a1['features']:
    if f['properties'].get('adm0_a3') != 'IND':
        continue
    g = shape(f['geometry']).buffer(0)
    if g.intersects(BBOX):
        states[f['properties']['name']] = g
names = sorted(states)
state_lines = []
for i, a in enumerate(names):
    for b in names[i+1:]:
        if states[a].distance(states[b]) > 0.01:
            continue
        s = states[a].boundary.intersection(states[b].buffer(0.002))
        s = s.intersection(BBOX)
        state_lines.extend(lines_of(s))
print('state lines:', len(state_lines))

india = countries['IND']

out = {
    "source": "Natural Earth 1:10m (public domain), admin-0 and admin-1 v5; simplified to ~1.3 km",
    "bbox": [60.0, 3.0, 104.0, 40.0],
    "land": rings_of(land),
    "borders": intl,
    "states": state_lines,
}
npts = sum(len(r) for r in out['land']) + sum(len(r) for r in out['borders']) + sum(len(r) for r in out['states'])
print('points:', npts)

# Land mask on the IMD 0.25 deg grid (India only), region 8-24N 74-90E, rows south->north
from shapely.prepared import prep
pi = prep(india)
from shapely.geometry import Point
mask = []
for r in range(65):
    lat = 8.0 + 0.25 * r
    for c in range(65):
        lon = 74.0 + 0.25 * c
        mask.append(1 if pi.contains(Point(lon, lat)) else 0)
print('india cells in domain:', sum(mask))
pass  # the UI land mask comes from the IMD grid via export-ui

js = "/* Base map for Resolve. " + out['source'] + ". Generated by build_geo.py */\nwindow.RESOLVE_GEO = " + json.dumps(out, separators=(',', ':')) + ";\n"
open(Path(__file__).resolve().parents[1] / 'geo' / 'region.js', 'w').write(js)
print('region.js bytes:', len(js))
